//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.10 at 11:25:11 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soap.springboot.vkakarla.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vkakarla.springboot.soap.interfaces;
